-- 회원 테이블의 관리자, 1번 유저로 등록
INSERT INTO USERS (USERNAME, USERID, USERPW, AUTHORITY)
VALUES ('admin', 'admin0000', '$2a$10$Naqxf0wgmdyA9Q4YHZaeM.Fwwp14ZlN3YOfwY92Gi9v9NQyEQ/yj.', 'ROLE_ADMIN');


-- 상품 테이블 예시
INSERT INTO Items (ITEM_NAME, PRICE, ITEM_SELL_STATUS, CATEGORY, SIZE, COLOR, PGENDER, STOCK)
VALUES  ('상품1', 10000, 'NORMAL', '101','L', 'BLACK','MAN', 3);

INSERT INTO Items (ITEM_NAME, PRICE, ITEM_SELL_STATUS, CATEGORY, SIZE, COLOR, PGENDER, STOCK)
VALUES  ('상품2', 10000, 'NORMAL', '101','L', 'BLACK','MAN', 3);

INSERT INTO Items (ITEM_NAME, PRICE, ITEM_SELL_STATUS, CATEGORY, SIZE, COLOR, PGENDER, STOCK)
VALUES  ('상품3', 10000, 'NORMAL', '102','L', 'BLACK','MAN', 3);

INSERT INTO Items (ITEM_NAME, PRICE, ITEM_SELL_STATUS, CATEGORY, SIZE, COLOR, PGENDER, STOCK)
VALUES  ('상품4', 10000, 'NORMAL', '102','L', 'BLACK','MAN', 3);

INSERT INTO Items (ITEM_NAME, PRICE, ITEM_SELL_STATUS, CATEGORY, SIZE, COLOR, PGENDER, STOCK)
VALUES  ('상품5', 10000, 'NORMAL', '102','L', 'BLACK','MAN', 3);

