-- 회원 테이블에 관리자 계정 1번으로
INSERT INTO USERS (USERNAME, USERID, USERPW, AUTHORITY)
VALUES ('admin', 'admin0000', '$2a$10$Naqxf0wgmdyA9Q4YHZaeM.Fwwp14ZlN3YOfwY92Gi9v9NQyEQ/yj.', 'ROLE_ADMIN');

INSERT INTO USERS (USERNAME, USERID, USERPW, AUTHORITY)
VALUES ('emily', 'emily123', '$2a$10$Naqxf0wgmdyA9Q4YHZaeM.Fwwp14ZlN3YOfwY92Gi9v9NQyEQ/yj.', 'ROLE_USER');

INSERT INTO USERS (USERNAME, USERID, USERPW, AUTHORITY)
VALUES ('testuser', 'testuser0000', '$2a$10$Naqxf0wgmdyA9Q4YHZaeM.Fwwp14ZlN3YOfwY92Gi9v9NQyEQ/yj.', 'ROLE_USER');



-- 상품 테이블
INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품1','101',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품2','101',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품3','102',3, 10000, 'BLACK', 'MAN', 'SOLD_OUT', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품4','102',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품5','102',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품6','103',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

INSERT INTO ITEM(ITEM_NAME, CATEGORY,STOCK, PRICE, COLOR, PGENDER, ITEM_SELL_STATUS, ITEM_DETAIL)
VALUES ('상품7','103',3, 10000, 'BLACK', 'MAN', 'NORMAL', '상품 설명');

-- 상품 사이즈
INSERT INTO ITEM_SIZE (size_Name, product_id)
VALUES
    ('S', 1),
    ('M', 1),
    ('XL',1),
    ('L', 2);

-- 상품 색상
INSERT INTO ITEM_Color (color, product_id)
VALUES
    ('black', 1),
    ('white', 1),
    ('grey',1),
    ('red', 2),
    ('yellow', 2);